[package]
name = "fibsterm"
version = "0.1.0"
authors = ["Ryan DV <general@ryandv.me>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
termion = "1.5.6"
